model = "gpt-5.4"
model_reasoning_effort = "medium"

[projects."/Users/dan/src/temporal-all/.git/modules/repos"]
trust_level = "trusted"

[projects."/Users/dan/src/devenv/tools"]
trust_level = "trusted"

[projects."/Users/dan/src/temporal-all/repos/temporal"]
trust_level = "trusted"

[projects."/Users/dan/src/temporal-all/repos/sdk-go"]
trust_level = "trusted"

[projects."/Users/dan/src/wormhole"]
trust_level = "trusted"

[projects."/Users/dan/src/todo"]
trust_level = "trusted"

[projects."/Users/dan/src/temporal-all/repos/api"]
trust_level = "trusted"

[mcp_servers.notion]
url = "https://mcp.notion.com/mcp"
